"""add language to posts

Revision ID: 9913c457dc3e
Revises: 1a3bd2c1bc1f
Create Date: 2018-11-01 15:36:23.870638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9913c457dc3e'
down_revision = '1a3bd2c1bc1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
